<a href="https://colab.research.google.com/github/MADHUPRIYAAA/2303a51583-batch-22/blob/main/lab%203.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

# Generate 4x4 array with random test scores (0-100)
scores = np.random.randint(50, 100, size=(4, 4))
print("Test Scores (4x4 array):\n", scores)
# Row-wise and Column-wise Means
row_means = np.mean(scores, axis=1)
col_means = np.mean(scores, axis=0)
print("\nRow-wise Means:", row_means)
print("Column-wise Means:", col_means)
# Standard Deviation and Variance
std_dev = np.std(scores)
variance = np.var(scores)
print("\nStandard Deviation:", std_dev)
print("Variance:", variance)
# Global max, min, and their indices
global_max = np.max(scores)
global_min = np.min(scores)
max_index = np.unravel_index(np.argmax(scores), scores.shape)
min_index = np.unravel_index(np.argmin(scores), scores.shape)
print("\nGlobal Max:", global_max, "at index", max_index)
print("Global Min:", global_min, "at index", min_index)
# Summary
print("\nSummary:")
print(f"Row means: {row_means}")
print(f"Column means: {col_means}")
print(f"Std Dev: {std_dev:.2f}, Variance: {variance:.2f}")
print(f"Max value {global_max} at {max_index}, Min value {global_min} at {min_index}")


Test Scores (4x4 array):
 [[90 67 53 55]
 [68 98 88 90]
 [58 69 54 55]
 [72 91 95 78]]

Row-wise Means: [66.25 86.   59.   84.  ]
Column-wise Means: [72.   81.25 72.5  69.5 ]

Standard Deviation: 15.736973779923508
Variance: 247.65234375

Global Max: 98 at index (np.int64(1), np.int64(1))
Global Min: 53 at index (np.int64(0), np.int64(2))

Summary:
Row means: [66.25 86.   59.   84.  ]
Column means: [72.   81.25 72.5  69.5 ]
Std Dev: 15.74, Variance: 247.65
Max value 98 at (np.int64(1), np.int64(1)), Min value 53 at (np.int64(0), np.int64(2))


In [2]:
import numpy as np
# Create a 3x3x3 RGB image array with pixel values 0–255
image = np.random.randint(0, 256, size=(3, 3, 3))
print("Original Image (3x3x3):\n", image)
# Extract Red, Green, Blue channels
red_channel = image[:, :, 0]
green_channel = image[:, :, 1]
blue_channel = image[:, :, 2]
print("\nRed Channel:\n", red_channel)
print("Green Channel:\n", green_channel)
print("Blue Channel:\n", blue_channel)
# Average intensity per channel
avg_red = np.mean(red_channel)
avg_green = np.mean(green_channel)
avg_blue = np.mean(blue_channel)
print("\nAverage Intensities:")
print(f"Red: {avg_red:.2f}, Green: {avg_green:.2f}, Blue: {avg_blue:.2f}")
# Brighten image by adding 50 (clip at 255)
brightened = np.clip(image + 50, 0, 255)
print("\nBrightened Image (clipped at 255):\n", brightened)


Original Image (3x3x3):
 [[[  2 215  48]
  [ 78 203 203]
  [148 195 120]]

 [[ 40  98  62]
  [  8 231  56]
  [ 54 130 160]]

 [[237 148 240]
  [196  90 254]
  [255 211  88]]]

Red Channel:
 [[  2  78 148]
 [ 40   8  54]
 [237 196 255]]
Green Channel:
 [[215 203 195]
 [ 98 231 130]
 [148  90 211]]
Blue Channel:
 [[ 48 203 120]
 [ 62  56 160]
 [240 254  88]]

Average Intensities:
Red: 113.11, Green: 169.00, Blue: 136.78

Brightened Image (clipped at 255):
 [[[ 52 255  98]
  [128 253 253]
  [198 245 170]]

 [[ 90 148 112]
  [ 58 255 106]
  [104 180 210]]

 [[255 198 255]
  [246 140 255]
  [255 255 138]]]
