<a href="https://colab.research.google.com/github/MADHUPRIYAAA/2303a51583-batch-22/blob/main/labcodes%203.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [18]:
fp = open("example.txt","w")
fp.write("Hello, B.Tech students!\n")
fp.write("This is file handling in python.\n")
fp.write("sr university\n")
fp.write("madhupriya")
fp.close()
print("Data written successfully")

Data written successfully


In [19]:
file=open("example.txt","r")
content=file.read()
print("file content:\n",content)
file.close()

file content:
 Hello, B.Tech students!
This is file handling in python.
sr university
madhupriya


In [20]:
file=open("example.txt","r")
line1=file.readline()
print("first line:",line1)
line2=file.readline()
print("second line:",line2)
line3=file.readline()
print("third line:",line3)
file.close()

first line: Hello, B.Tech students!

second line: This is file handling in python.

third line: sr university



In [21]:
file=open("example.txt","r")
lines=file.readlines()
print("list of lines:",lines)
file.close()

list of lines: ['Hello, B.Tech students!\n', 'This is file handling in python.\n', 'sr university\n', 'madhupriya']


In [25]:
#appending data to an existing file
file=open("example.txt","a")
file.write("Appending new data..\n")
file.close()

In [26]:
#using with statement (best practice)
#the with statement automatically closes to
with open ("example.txt","r") as fp:
    data=fp.read()
    print(data)

Hello, B.Tech students!
This is file handling in python.
sr university
madhupriyaAppending new data..
.Appending new data..



In [27]:
#working with csv file
import csv
#writing to csv
with open("data.csv","w",newline='')as fp:
  wr=csv.writer(fp)
  wr.writerows([["Name","Age","course"],["aaa",21,"CSE"],["bbb",20,"ECE"]])

In [29]:
#reading from csv
with open("data.csv","r") as file:
  re=csv.reader(file)
  for row in re:
    print(row)

['Name', 'Age', 'course']
['aaa', '21', 'CSE']
['bbb', '20', 'ECE']


In [36]:
import numpy as np
#1D Array
arr1=np.array([1,2,3,4])
print("1D array:",arr1)
#2d array
arr2=np.array([[1,2,3],[4,5,6]])
print("2D array:\n",arr2)
#zeros Array
zerors_arr=np.zeros((3,3))
print("zeros array:\n",zerors_arr)
#ones array
ones_arr=np.ones((3,3))
print("ones array:\n",ones_arr)
#range of number
range_arr=np.arange(0,10,2)
#start,stop,step
print("range array:",range_arr)
#Random Array
rand_arr=np.random.rand(3,3)
print("Random array:\n",rand_arr)

1D array: [1 2 3 4]
2D array:
 [[1 2 3]
 [4 5 6]]
zeros array:
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
ones array:
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
range array: [0 2 4 6 8]
Random array:
 [[0.19685341 0.55058028 0.63814278]
 [0.74206755 0.98825059 0.56520504]
 [0.38125039 0.5787708  0.56721689]]


In [38]:
#Array Attribute
arr=np.array([[1,2,3],[4,5,6]])
print("shape of array:",arr.shape)
print("size of array:",arr.size)
print("dimension of array:",arr.ndim)
print("data type of array:",arr.dtype)
print("item size:",arr.itemsize)

shape of array: (2, 3)
size of array: 6
dimension of array: 2
data type of array: int64
item size: 8


In [39]:
#array index and slicing
arr=np.array([10,20,30,40,50])
print("first element:",arr[0])
print("last element:",arr[-1])
print("slicing:",arr[1:4])
print("every second elemet :",arr[::2])

first element: 10
last element: 50
slicing: [20 30 40]
every second elemet : [10 30 50]


In [40]:
#2D indexing
arr2d=np.array([[1,2,3],[4,5,6]])
print("element at row 1,col1=2:",arr2[0,1])
print("second row:",arr2[1,:])
print("second column:",arr2[:,1])

element at row 1,col1=2: 2
second row: [4 5 6]
second column: [2 5]


In [41]:
#array operations
#arthmetic operations
a=np.array([1,2,3])
b=np.array([4,5,6])
print("addition:",a+b)
print("subtraction:",a-b)
print("multiplication:",a*b)
print("division:",a/b)
print("power:",a**2)

addition: [5 7 9]
subtraction: [-3 -3 -3]
multiplication: [ 4 10 18]
division: [0.25 0.4  0.5 ]
power: [1 4 9]


In [44]:
#Mathemaitcal Functions
arr = np.array([1,2,3])
print("sin",np.sin(arr))
print("cos",np.cos(arr))
print("tan",np.tan(arr))
print("log",np.log(arr))
print("exp",np.exp(arr))

sin [0.84147098 0.90929743 0.14112001]
cos [ 0.54030231 -0.41614684 -0.9899925 ]
tan [ 1.55740772 -2.18503986 -0.14254654]
log [0.         0.69314718 1.09861229]
exp [ 2.71828183  7.3890561  20.08553692]


In [43]:
#aggregat functions
arr=np.array([[1,2,3],[4,5,6]])
print("sum of all elements:",np.sum(arr))
print("minimum value:",np.min(arr))
print("maximum value:",np.max(arr))
print("mean value:",np.mean(arr))
print("median value:",np.median(arr))
print("standard deviation:",np.std(arr))
print("sum along axis 0:",np.sum(arr,axis=0))
print("sum along axis 1:",np.sum(arr,axis=1))

sum of all elements: 21
minimum value: 1
maximum value: 6
mean value: 3.5
median value: 3.5
standard deviation: 1.707825127659933
sum along axis 0: [5 7 9]
sum along axis 1: [ 6 15]


In [46]:
#broad casting
a=np.array([1,2,3])
b=5
print("broadcasting:\n",a+b)
c=np.array([[1],[2],[3]])
d=np.array([4,5,6])
print("broadcasting:\n",c+d)

broadcasting:
 [6 7 8]
broadcasting:
 [[5 6 7]
 [6 7 8]
 [7 8 9]]


In [50]:
#matrix operations
a=np.array([[1,2],[3,4]])
b=np.array([[5,6],[7,8]])
print("matrix multipication:\n",np.dot(a,b))
print("transpose:\n",a.T)
print("inverse:\n",np.linalg.inv(a))
print("determinant:\n",np.linalg.det(a))


matrix multipication:
 [[19 22]
 [43 50]]
transpose:
 [[1 3]
 [2 4]]
inverse:
 [[-2.   1. ]
 [ 1.5 -0.5]]
determinant:
 -2.0000000000000004


In [51]:
#sample program student marks
import numpy as np
marks = np.array([
[85, 90, 88],
[78, 81, 85],
[92, 89, 95]
])
print("Average marks per student:", np.mean(marks, axis=1))
print("Average marks per subject:", np.mean(marks, axis=0))
print("Highest marks in each subject:", np.max(marks, axis=0))
print("Lowest marks in each subject:", np.min(marks, axis=0))

Average marks per student: [87.66666667 81.33333333 92.        ]
Average marks per subject: [85.         86.66666667 89.33333333]
Highest marks in each subject: [92 90 95]
Lowest marks in each subject: [78 81 85]
